name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      rabbitmq:
        image: rabbitmq:3.11-management
        ports:
          - 15672:15672
          - 5672:5672

    strategy:
      matrix:
        go: ["1.18", "1.19"]

    steps:
    - name: CHECKOUT
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Print Go version
      run: go version
    - name: Configure broker
      run: RABBITHOLE_RABBITMQCTL=DOCKER:${{job.services.rabbitmq.id}} bin/ci/before_build.sh
    - name: Await node startup
      run: rabbitmqctl await_startup --timeout 60
    - name: Run tests
      run: make
